### ISSUE TITLE
Compatibility with AEMaaCS

### ISSUE THREAD

**Issue by kwin** [ist-dresden/composum-nodes#237]
Currently when trying to deploy Composum Nodes on AEM as a Cloud service the following errors are emitted:

```
19.03.2021 02:56:13.558 [cm-p29008-e106842-aem-publish-748769766d-rs4bh] *ERROR* [Apache Sling Repository Startup Thread #1] org.apache.sling.jcr.contentloader.internal.ContentLoaderService Problem loading initial content of bundle com.composum.core.usermgnt (573)
java.lang.UnsupportedOperationException: This builder is read-only.
	at org.apache.jackrabbit.oak.spi.state.ReadOnlyBuilder.unsupported(ReadOnlyBuilder.java:44) [org.apache.jackrabbit.oak-store-spi:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.spi.state.ReadOnlyBuilder.remove(ReadOnlyBuilder.java:110) [org.apache.jackrabbit.oak-store-spi:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.core.SecureNodeBuilder.remove(SecureNodeBuilder.java:166) [org.apache.jackrabbit.oak-core:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.plugins.tree.impl.AbstractMutableTree.remove(AbstractMutableTree.java:51) [org.apache.jackrabbit.oak-core:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.core.MutableTree.remove(MutableTree.java:184) [org.apache.jackrabbit.oak-core:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.jcr.delegate.NodeDelegate.remove(NodeDelegate.java:701) [org.apache.jackrabbit.oak-jcr:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl$4.performVoid(NodeImpl.java:242) [org.apache.jackrabbit.oak-jcr:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.performVoid(SessionDelegate.java:275) [org.apache.jackrabbit.oak-jcr:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.remove(NodeImpl.java:235) [org.apache.jackrabbit.oak-jcr:1.39.0.R1886624]
	at org.apache.sling.jcr.contentloader.internal.BundleContentLoader.createFolder(BundleContentLoader.java:509) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.BundleContentLoader.installFromPath(BundleContentLoader.java:364) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.BundleContentLoader.installContent(BundleContentLoader.java:238) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.BundleContentLoader.registerBundleInternal(BundleContentLoader.java:148) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.BundleContentLoader.registerBundle(BundleContentLoader.java:95) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.ContentLoaderService.activate(ContentLoaderService.java:244) [org.apache.sling.jcr.contentloader:2.3.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:244) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:685) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:529) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:318) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:308) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:354) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:1000) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:973) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:785) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1271) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1222) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1200) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1121) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:928) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:864) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1152) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:114) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
	at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4833)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3804)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:328)
	at org.apache.sling.jcr.base.AbstractSlingRepositoryManager.registerService(AbstractSlingRepositoryManager.java:222) [org.apache.sling.jcr.base:3.1.6]
	at org.apache.sling.jcr.base.AbstractSlingRepositoryManager.initializeAndRegisterRepositoryService(AbstractSlingRepositoryManager.java:566) [org.apache.sling.jcr.base:3.1.6]
	at org.apache.sling.jcr.base.AbstractSlingRepositoryManager.access$300(AbstractSlingRepositoryManager.java:92) [org.apache.sling.jcr.base:3.1.6]
	at org.apache.sling.jcr.base.AbstractSlingRepositoryManager$4.run(AbstractSlingRepositoryManager.java:527) [org.apache.sling.jcr.base:3.1.6]
```

```
19.03.2021 02:56:13.594 [cm-p29008-e106842-aem-publish-748769766d-rs4bh] *ERROR* [Apache Sling Repository Startup Thread #1] org.apache.sling.jcr.contentloader.internal.ContentLoaderService Problem loading initial content of bundle com.composum.core.jslibs (575)
java.lang.UnsupportedOperationException: This builder is read-only.
	at org.apache.jackrabbit.oak.spi.state.ReadOnlyBuilder.unsupported(ReadOnlyBuilder.java:44) [org.apache.jackrabbit.oak-store-spi:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.spi.state.ReadOnlyBuilder.setProperty(ReadOnlyBuilder.java:167) [org.apache.jackrabbit.oak-store-spi:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.core.SecureNodeBuilder.setProperty(SecureNodeBuilder.java:256) [org.apache.jackrabbit.oak-core:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.plugins.tree.impl.AbstractMutableTree.setProperty(AbstractMutableTree.java:174) [org.apache.jackrabbit.oak-core:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.core.MutableTree.setProperty(MutableTree.java:224) [org.apache.jackrabbit.oak-core:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.jcr.delegate.NodeDelegate.setProperty(NodeDelegate.java:535) [org.apache.jackrabbit.oak-jcr:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl$36.perform(NodeImpl.java:1403) [org.apache.jackrabbit.oak-jcr:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl$36.perform(NodeImpl.java:1390) [org.apache.jackrabbit.oak-jcr:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.perform(SessionDelegate.java:209) [org.apache.jackrabbit.oak-jcr:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.jcr.session.ItemImpl.perform(ItemImpl.java:112) [org.apache.jackrabbit.oak-jcr:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.internalSetProperty(NodeImpl.java:1390) [org.apache.jackrabbit.oak-jcr:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.setProperty(NodeImpl.java:368) [org.apache.jackrabbit.oak-jcr:1.39.0.R1886624]
	at org.apache.sling.jcr.contentloader.internal.DefaultContentCreator.createProperty(DefaultContentCreator.java:586) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.DefaultContentCreator.createFileAndResourceNode(DefaultContentCreator.java:660) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.BundleContentLoader.createFile(BundleContentLoader.java:547) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.BundleContentLoader.handleFile(BundleContentLoader.java:428) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.BundleContentLoader.installFromPath(BundleContentLoader.java:374) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.BundleContentLoader.installContent(BundleContentLoader.java:238) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.BundleContentLoader.registerBundleInternal(BundleContentLoader.java:148) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.BundleContentLoader.registerBundle(BundleContentLoader.java:95) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.ContentLoaderService.activate(ContentLoaderService.java:244) [org.apache.sling.jcr.contentloader:2.3.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:244) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:685) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:529) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:318) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:308) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:354) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:1000) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:973) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:785) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1271) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1222) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1200) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1121) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:928) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:864) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1152) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:114) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
	at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4833)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3804)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:328)
	at org.apache.sling.jcr.base.AbstractSlingRepositoryManager.registerService(AbstractSlingRepositoryManager.java:222) [org.apache.sling.jcr.base:3.1.6]
	at org.apache.sling.jcr.base.AbstractSlingRepositoryManager.initializeAndRegisterRepositoryService(AbstractSlingRepositoryManager.java:566) [org.apache.sling.jcr.base:3.1.6]
	at org.apache.sling.jcr.base.AbstractSlingRepositoryManager.access$300(AbstractSlingRepositoryManager.java:92) [org.apache.sling.jcr.base:3.1.6]
	at org.apache.sling.jcr.base.AbstractSlingRepositoryManager$4.run(AbstractSlingRepositoryManager.java:527) [org.apache.sling.jcr.base:3.1.6]
```

```
19.03.2021 02:56:13.701 [cm-p29008-e106842-aem-publish-748769766d-rs4bh] *ERROR* [Apache Sling Repository Startup Thread #1] org.apache.sling.jcr.contentloader.internal.BundleContentLoader Cannot load initial content for bundle com.composum.core.console : This builder is read-only.
javax.jcr.RepositoryException: This builder is read-only.
	at org.apache.sling.jcr.contentloader.internal.BundleContentLoader.createNode(BundleContentLoader.java:490) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.BundleContentLoader.handleFile(BundleContentLoader.java:414) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.BundleContentLoader.installFromPath(BundleContentLoader.java:374) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.BundleContentLoader.installContent(BundleContentLoader.java:238) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.BundleContentLoader.registerBundleInternal(BundleContentLoader.java:148) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.BundleContentLoader.registerBundle(BundleContentLoader.java:95) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.ContentLoaderService.activate(ContentLoaderService.java:244) [org.apache.sling.jcr.contentloader:2.3.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:244) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:685) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:529) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:318) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:308) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:354) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:1000) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:973) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:785) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1271) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1222) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1200) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1121) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:928) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:864) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1152) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:114) [org.apache.felix.scr:2.1.26]
	at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
	at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4833)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3804)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:328)
	at org.apache.sling.jcr.base.AbstractSlingRepositoryManager.registerService(AbstractSlingRepositoryManager.java:222) [org.apache.sling.jcr.base:3.1.6]
	at org.apache.sling.jcr.base.AbstractSlingRepositoryManager.initializeAndRegisterRepositoryService(AbstractSlingRepositoryManager.java:566) [org.apache.sling.jcr.base:3.1.6]
	at org.apache.sling.jcr.base.AbstractSlingRepositoryManager.access$300(AbstractSlingRepositoryManager.java:92) [org.apache.sling.jcr.base:3.1.6]
	at org.apache.sling.jcr.base.AbstractSlingRepositoryManager$4.run(AbstractSlingRepositoryManager.java:527) [org.apache.sling.jcr.base:3.1.6]
Caused by: java.lang.UnsupportedOperationException: This builder is read-only.
	at org.apache.jackrabbit.oak.spi.state.ReadOnlyBuilder.unsupported(ReadOnlyBuilder.java:44) [org.apache.jackrabbit.oak-store-spi:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.spi.state.ReadOnlyBuilder.remove(ReadOnlyBuilder.java:110) [org.apache.jackrabbit.oak-store-spi:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.core.SecureNodeBuilder.remove(SecureNodeBuilder.java:166) [org.apache.jackrabbit.oak-core:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.plugins.tree.impl.AbstractMutableTree.remove(AbstractMutableTree.java:51) [org.apache.jackrabbit.oak-core:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.core.MutableTree.remove(MutableTree.java:184) [org.apache.jackrabbit.oak-core:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.jcr.delegate.NodeDelegate.remove(NodeDelegate.java:701) [org.apache.jackrabbit.oak-jcr:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl$4.performVoid(NodeImpl.java:242) [org.apache.jackrabbit.oak-jcr:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.performVoid(SessionDelegate.java:275) [org.apache.jackrabbit.oak-jcr:1.39.0.R1886624]
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.remove(NodeImpl.java:235) [org.apache.jackrabbit.oak-jcr:1.39.0.R1886624]
	at org.apache.sling.jcr.contentloader.internal.DefaultContentCreator.createNode(DefaultContentCreator.java:231) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.readers.JsonReader.createNode(JsonReader.java:225) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.readers.JsonReader.parse(JsonReader.java:177) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.readers.JsonReader.parse(JsonReader.java:156) [org.apache.sling.jcr.contentloader:2.3.0]
	at org.apache.sling.jcr.contentloader.internal.BundleContentLoader.createNode(BundleContentLoader.java:484) [org.apache.sling.jcr.contentloader:2.3.0]
	... 39 common frames omitted
```

and similar ones for the other bundles.
See also the related discussion in https://lists.apache.org/thread.html/r1162d545922381187a0530f838b684b60f2a8ea28a12649ae79372e8%40%3Cdev.sling.apache.org%3E.

**Comment by kwin** [comment]
The new package cannot be deployed with CloudManager AEMaaCS due to OSGi configuration below unsupported node name "install"
```
[ERROR] Unable to convert content-package [/....zip]: OSGi configuration are only considered if placed below a folder called 'config', but the configuration at '/jcr_root/libs/composum/nodes/install/org.apache.sling.jcr.base.internal.LoginAdminWhitelist.fragment-composum_core_v2.config' is placed outside!
```

Compare with https://issues.apache.org/jira/browse/SLING-10278.

**Comment by kwin** [comment]
The latter seems to be fixed in https://github.com/ist-dresden/composum-nodes/commit/6905b9d2c5baa70b680e247af78fe40a31a5544d.

**Comment by royteeuwen** [comment]
@ist-rw @kwin  Actually AEMaaCS is still an issue seeing as there should be no installation under /libs, this makes the quality gates fail. Not sure if that is something you are willing to refactor

**Comment by kwin** [comment]
@ist-rw You should probably integrate https://github.com/adobe/aemanalyser-maven-plugin/tree/main/aemanalyser-maven-plugin in your Maven build (maybe with a dedicated profile) to check against AEMaaCS compatibility.

**Comment by ist-rw** [comment]
I know this - but NO! - sorry.
I tried to migrate to '/apps' for the AEM package variant but without success. There is no quick solution and it is a lot of work. Invest this time here is currently not possible.

**Comment by royteeuwen** [comment]
@ist-rw  would it be ok if we contribute this (if we find the time?) or is there a reason that changing it only in composum-nodes would still pose issues in other frameworks (like pages)

**Comment by ist-rw** [comment]
@royteeuwen @kwin
Ok, I've heard the shout outs....
I exhumed the branch for adapting the AEM package to the cloud rules (transformation to '/apps') again. After another 500 customizations and deep into the night, a seemingly runnable state was reached.
It is available in advance in the branch 'feature/aem-cloud-apps'. The resolver root of the Composum nodes can now be configured. This is done in the AEM package and all app resources are moved from '/libs' to '/apps' in this variant. This leaves the general Sling base in '/libs' and for AEM there is then the '/apps' variant. The AEM Analyzer integrated into the build still produces 8 warnings, I could live with those.
But now more extensive testing is needed for both variants before this can become a release. Support would be appreciated here.

**Comment by ist-rw** [comment]
If an existing instance has the Nodes installed in 'libs' this installation should be removed before installing the 'apps' based variant. A 'cleanup' package has been prepared to remove Composum via package installation.

**Comment by royteeuwen** [comment]
@ist-rw awesome ;)! thanks for the hard work, will definitely test it, as said I don't mind helping out :D

**Comment by royteeuwen** [comment]
Updated to commons collections 4 to solve an extra warning:
https://github.com/ist-dresden/composum-nodes/pull/276

**Comment by royteeuwen** [comment]
@ist-rw  any chance to do a review and of doing a release for this?
